create schema if not exists verity;

revoke all on schema verity from public, anon, authenticated;

create table verity.runs (
    id text primary key,
    question text not null,
    status text not null check (
        status in ('queued', 'running', 'completed', 'failed', 'cancelled')
    ),
    record_json jsonb not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index runs_created_at_idx on verity.runs (created_at desc);
create index runs_status_idx on verity.runs (status);

create table verity.run_events (
    seq bigint generated by default as identity primary key,
    run_id text not null references verity.runs (id) on delete cascade,
    type text not null,
    data_json jsonb not null,
    created_at timestamptz not null default now()
);

create index run_events_run_seq_idx on verity.run_events (run_id, seq);

alter table verity.runs enable row level security;
alter table verity.run_events enable row level security;

revoke all on all tables in schema verity from public, anon, authenticated;
revoke all on all sequences in schema verity from public, anon, authenticated;
